## code to prepare `Azores reference test files` dataset goes here

# The files generated by this script are used for reference testing. The output
# of this script was copied to tests/testthat/testdata/ so as to be accessed
# by R CHECK
seeds <- 1:5
data(Azores, package = "relaxedDAISIE")
data_name <- "Azores"
models <- c("cr_dd", "cr_di")
cond <- 1

for (model in models) {
  for (seed in seeds) {
    run_daisie_ml(
      data = Azores,
      data_name = data_name,
      model = model,
      seed = seed,
      cond = cond)
  }
}

for (seed in seeds) {
  bootstrap(
    data = Azores,
    data_name = data_name,
    model_1 = "cr_dd",
    model_2 = "cr_di",
    seed = seed,
    cond = cond
  )
}
