## code to prepare `Comoros reference test files` dataset goes here

# The files generated by this script are used for reference testing. The output
# of this script was copied to tests/testthat/testdata/results/Comoros so as to
# be accessed by R CHECK
array_indices <- 1:3
data(Comoros, package = "relaxedDAISIE")
models <- c("cr_dd", "cr_di")
cond <- 1

for (model in models) {
  for (array_index in array_indices) {
    run_daisie_ml(
      data = Comoros,
      data_name = "Comoros",
      model = model,
      array_index = array_index,
      cond = cond,
      test = TRUE
    )
  }
}
