#' Checks if jobs were run with the same seed
#'
#' Checks every log file inside a folder for the record of the used seed.
#' Returns duplicated seeds and corresponding job arrays.
#'
#' @inheritParams default_params_doc
#'
#' @return A named list with two elements.
#'   * `duplicated_seeds`: A character vector with the seed values that were
#'   found to be duplicated within the folder. Will be empty if no duplicates
#'   were found
#'   * `duplicated_array_indices`: A numeric vector with corresponding array
#'   indices. Will be empty if no duplicates were found.
#' @export
#' @author Pedro Neves
#'
#' @note
#' This function is the preferred method for checking for the presence of
#' repeated seeds.
#' However, it will fail if the log files were generated by older versions of
#' the package, as it expects that the seed and array information are always at
#' the same location. If you encounter issues, try running
#' [check_repeated_seeds_long()] instead. For all other cases, give preference
#' to this function as better optimization for log output parsing is possible.
#'
#' @seealso [check_repeated_seeds_long()] for deprecated checking compatible
#' with older log files.
#'
#' @examples
#' \dontrun{
#' repeated_seeds <- check_repeated_seeds(logs_path = "/logs/")
#' }
check_repeated_seeds <- function(logs_path) {
  testit::assert(fact = "Folder exists", dir.exists(logs_path))

  logfiles <- list.files(logs_path, full.names = TRUE)
  testit::assert(fact = "Folder has logfiles", length(logfiles) >= 1)

  log_heads <- lapply(logfiles, readLines, n = 5)

  array_indices <- c()
  seeds <- c()
  for (i in seq_along(log_heads)) {
    array_line <- log_heads[[i]][4]
    seed_line <- log_heads[[i]][5]
    testit::assert(
      fact = "Array line found. Try check_repeated_seeds_long() if this fails",
      grepl("Running analysis with array index:", array_line))
    testit::assert(
      fact = "Seed line found. Try check_repeated_seeds_long() if this fails",
      grepl("Running analysis with seed:", seed_line))

    array_indices[i] <- sub(".*: ", "", array_line)
    seeds[i] <- sub(".*: ", "", seed_line)
  }

  duplicated_seeds <- seeds[duplicated(seeds)]
  duplicated_seed_indices <- which(duplicated(seeds))
  duplicated_array_indices <- array_indices[duplicated_seed_indices]

  return(list(
    duplicated_seeds = duplicated_seeds,
    duplicated_array_indices = duplicated_array_indices
  ))
}
